module.exports = {
  black: "#4A2F48",
  background: "#2B1D42",
  white: "#FAF7F2",
  foreground: "#FFFAEE",
  red: "#CD5B6F",
  green: "#F3B88D",
  yellow: "#FCECCB",
  blue: "#CD5B6F",
  magenta: "#F3B88D",
  cyan: "#FCECCB",
  light: {
    black: "#4A2F48",
    background: "#FCECCB",
    white: "#F1F1F1",
    foreground: "#1f1f28",
    red: "#CD5B6F",
    green: "#F3B88D",
    yellow: "#A17F9F",
    blue: "#CD5B6F",
    magenta: "#F3B88D",
    cyan: "#A17F9F",
  },
};
